### ISSUE TITLE
View different annotation options

### ISSUE THREAD

**Issue by bpmweel** [FEDMix/eshmun#19]
## Story
As a Clinician
I want have a preview of the different annotation options that are available to me
So that I can choose one to preview in the larger view

## Tasks

- [x]  Create thumbnail preview slider with next & prev button
- [x]  load annotation into slider
- [x] Add styles to preview slider
- [x] Make preview slider responsive

## Related
- For selecting a particular one see #22 
- Update on orthogonal view change see #21

## Technical Decisions
- [x] Annotations stored in a directory called 'annotations' which holds directories with different annotation options 

## Acceptance Criteria
- [ ] Create Tests for preview and next buttons  
- [ ] Test whether scans are loaded

## Designs
![Orthogonal_view](https://user-images.githubusercontent.com/16776108/115703673-b399e400-a36a-11eb-8154-4cc508a23753.png)
